# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$golang\
$ruby\
$lua\
$rust\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[ruby]
format = '[$symbol($version) ]($style)'
detect_files = ['Gemfile', '.ruby-version']
detect_variables = []
detect_extensions = []

[lua]
format = '[$symbol($version) ]($style)'

[rust]
format = '[$symbol($version) ]($style)'
