import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[shell]
program = "/bin/bash"
args = ["tmux", ""]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = 'full'

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 12

[colors]
draw_bold_text_with_bright_colors = true

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"
